### ISSUE TITLE
抖音采集脚本执行报错ModuleNotFoundError: No module named 'www_douyin_com'

### ISSUE THREAD

**Issue by sdfsky** [hacksman/spider_world#1]
执行
python3 douyin_crawl.py 
报错：
Traceback (most recent call last):
  File "douyin_crawl.py", line 12, in <module>
    from www_douyin_com.common.utils import *
ModuleNotFoundError: No module named 'www_douyin_com'

是我的配置问题吗，python小白请指教 ：）

python版本3.7.0

**Comment by hacksman** [comment]
> 执行
> python3 douyin_crawl.py
> 报错：
> Traceback (most recent call last):
> File "douyin_crawl.py", line 12, in 
> from www_douyin_com.common.utils import *
> ModuleNotFoundError: No module named 'www_douyin_com'
> 
> 是我的配置问题吗，python小白请指教 ：）
> 
> python版本3.7.0

这个问题已经修复了，可以拷贝下代码再试下

**Comment by sdfsky** [comment]
已经解决了，感谢：）

**Comment by sdfsky** [comment]
> > 执行
> > python3 douyin_crawl.py
> > 报错：
> > Traceback (most recent call last):
> > File "douyin_crawl.py", line 12, in
> > from www_douyin_com.common.utils import *
> > ModuleNotFoundError: No module named 'www_douyin_com'
> > 是我的配置问题吗，python小白请指教 ：）
> > python版本3.7.0
> 
> 这个问题已经修复了，可以拷贝下代码再试下

已经解决了，非常感谢 ：）
