### ISSUE TITLE
缺少token

### ISSUE THREAD

**Issue by pikaqqqqqq** [hacksman/spider_world#20]
Traceback (most recent call last):
  File "video_download_run.py", line 13, in <module>
    douyin_crawl = DouyinCrawl()
TypeError: __init__() missing 1 required positional argument: 'token'

**Comment by hacksman** [comment]
> Traceback (most recent call last):
> File "video_download_run.py", line 13, in 
> douyin_crawl = DouyinCrawl()
> TypeError: **init**() missing 1 required positional argument: 'token'

直接在这里看最下方启动的方式：https://github.com/hacksman/spider_world/blob/master/www_douyin_com/spiders/douyin_crawl.py

**Comment by xychy** [comment]
关注公众号获取token值替换运行后，提示：TypeError: init() missing 1 required positional argument: 'token'
