### ISSUE TITLE
爬取抖音报错提示缺少token

### ISSUE THREAD

**Issue by xychy** [hacksman/spider_world#23]
关注公众号获取token值替换运行后，提示：TypeError: init() missing 1 required positional argument: 'token'

**Comment by hacksman** [comment]
你说下下你的详细运行步骤

**Comment by xychy** [comment]
D:\Python36\python.exe F:/git仓库/spider_world.git/www_douyin_com/spiders/douyin_crawl.py
{'ssid': '', 'server_time': 1555895972, 'device_id': 67504176840, 'install_id': 70194891570, 'new_user': 1, 'openudid': '5021130248699783', 'android_id': 'db7946c5af8320e1', 'uuid': '679828350176315', 'iid': 70194891570}
Exception <class 'requests.exceptions.ConnectionError'> occurred retrying...
Exception <class 'requests.exceptions.ConnectionError'> occurred retrying...
Traceback (most recent call last):
  File "F:/git仓库/spider_world.git/www_douyin_com/spiders/douyin_crawl.py", line 338, in <module>
    douyin.download_one_video(aweme_id)
  File "F:/git仓库/spider_world.git/www_douyin_com/spiders/douyin_crawl.py", line 304, in download_one_video
    video_content = self.download_video(aweme_id)
  File "F:/git仓库/spider_world.git/www_douyin_com/spiders/douyin_crawl.py", line 285, in download_video
Exception <class 'requests.exceptions.ConnectionError'> occurred retrying...
    timeout=3).json()
AttributeError: 'dict' object has no attribute 'json'

**Comment by hacksman** [comment]
> D:\Python36\python.exe F:/git仓库/spider_world.git/www_douyin_com/spiders/douyin_crawl.py
> {'ssid': '', 'server_time': 1555895972, 'device_id': 67504176840, 'install_id': 70194891570, 'new_user': 1, 'openudid': '5021130248699783', 'android_id': 'db7946c5af8320e1', 'uuid': '679828350176315', 'iid': 70194891570}
> Exception <class 'requests.exceptions.ConnectionError'> occurred retrying...
> Exception <class 'requests.exceptions.ConnectionError'> occurred retrying...
> Traceback (most recent call last):
> File "F:/git仓库/spider_world.git/www_douyin_com/spiders/douyin_crawl.py", line 338, in 
> douyin.download_one_video(aweme_id)
> File "F:/git仓库/spider_world.git/www_douyin_com/spiders/douyin_crawl.py", line 304, in download_one_video
> video_content = self.download_video(aweme_id)
> File "F:/git仓库/spider_world.git/www_douyin_com/spiders/douyin_crawl.py", line 285, in download_video
> Exception <class 'requests.exceptions.ConnectionError'> occurred retrying...
> timeout=3).json()
> AttributeError: 'dict' object has no attribute 'json'

你启动的时候将配置文件里面的 token 换成你自己拿到的 token，每日请求次数有限制，你试一下就知道了

**Comment by hacksman** [comment]
> D:\Python36\python.exe F:/git仓库/spider_world.git/www_douyin_com/spiders/douyin_crawl.py
> {'ssid': '', 'server_time': 1555895972, 'device_id': 67504176840, 'install_id': 70194891570, 'new_user': 1, 'openudid': '5021130248699783', 'android_id': 'db7946c5af8320e1', 'uuid': '679828350176315', 'iid': 70194891570}
> Exception <class 'requests.exceptions.ConnectionError'> occurred retrying...
> Exception <class 'requests.exceptions.ConnectionError'> occurred retrying...
> Traceback (most recent call last):
> File "F:/git仓库/spider_world.git/www_douyin_com/spiders/douyin_crawl.py", line 338, in 
> douyin.download_one_video(aweme_id)
> File "F:/git仓库/spider_world.git/www_douyin_com/spiders/douyin_crawl.py", line 304, in download_one_video
> video_content = self.download_video(aweme_id)
> File "F:/git仓库/spider_world.git/www_douyin_com/spiders/douyin_crawl.py", line 285, in download_video
> Exception <class 'requests.exceptions.ConnectionError'> occurred retrying...
> timeout=3).json()
> AttributeError: 'dict' object has no attribute 'json'

已修复
