### ISSUE TITLE
用户id长度判断有问题

### ISSUE THREAD

**Issue by LukeDev2K** [hacksman/spider_world#3]
` if not re.findall('^\d{11}$', user_id) or not re.findall('^\d{12}$', user_id):
            self.logger.info("请输入正确的用户id， 用户id为11或12位纯数字...")
            return
`
判断 改成
`if not (re.findall('^\d{11}$', user_id) or re.findall('^\d{12}$', user_id)):
            self.logger.info("请输入正确的用户id， 用户id为11或12位纯数字...")
            return`

**Comment by hacksman** [comment]
谢谢指出，现已修正
